version: '3.8'

services:
  api:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-18-bookworm
    container_name: nestjs_application_redis_bull
    ports:
      - '3002:3002'
    volumes:
      - .:/api
    depends_on:
      - 'redis'

  postgres:
    container_name: nest-application-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest-application
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

  redis:
    image: redis:6.2.3-alpine
    container_name: nestjs_redis_bull_redis
    ports:
      - '6379:6379'
    environment:
      NODE_ENV: development
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '10M'

networks:
  default:
    name: nestjs_redis_bull_network_default
